# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\untitled\untitled81\untitled731（1）\untitled\untitled\Color_Select.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import re
from functools import partial

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QPushButton

selfcolor =[""] *24
selfcmya = [""] *24
selfprint = [""] * 24
yy = 0
cm = ""
yq = ""
class Ui_Color_Select(object):
    def setupUi(self, Color_Select):
        Color_Select.setObjectName("Color_Select")
        Color_Select.resize(440, 675)
        global ysn123
        ysn123 = Color_Select
        self.buttonBox = QtWidgets.QDialogButtonBox(Color_Select)
        self.buttonBox.setGeometry(QtCore.QRect(90, 630, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Color_Select)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 10, 300, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.default1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.default1.setObjectName("default1")
        self.layout.addWidget(self.default1)
        self.color_group = QtWidgets.QGridLayout()
        self.color_group.setContentsMargins(0, -1, -1, -1)
        self.color_group.setObjectName("color_group")
        colors = ["#80c7d9", "#f468c1", "#dfd759", "#a090bf",
                  "#af70ac", "#be5CA5", "#d25faa", "#e36b8e",
                  "#e16d80", "#df7C78", "#e19f71", "#c2d369",
                  "#a9cb7e", "#99c391", "#8dc5a8", "#8a9181",
                  "#955B6a", "#a33f59", "#bb2C4d", "#a0a172",
                  "#b2684e", "#ac9841", "#a8924e", "#cea23b"]
        buttons = ["", "", "", "", "",
                   "", "", "", "", "",
                   "", "", "", "", "",
                   "", "", "", "", "",
                   "", "", "", ""]
        position = [(i, j) for i in range(6) for j in range(4)]
        for pos, name1, name2 in zip(position, buttons, colors):
            button = QPushButton(name1)
            button.setStyleSheet("QPushButton{background:%s}" % str(name2))
            #            button.resize(50,10)
            index = colors.index(name2)
            button.setObjectName("buttonintable%s" % str(index))
            button.clicked.connect(partial(gettext,colors[index], button.objectName()))
            self.color_group.addWidget(button, *pos)
        self.layout.addLayout(self.color_group)
        self.selfdesigncolorgroup = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.selfdesigncolorgroup.setObjectName("selfdesigncolorgroup")
        self.layout.addWidget(self.selfdesigncolorgroup)
        self.selfdesigncolor_group = QtWidgets.QGridLayout()
        self.selfdesigncolor_group.setObjectName("selfdesigncolor_group")
        position1 = [(i, j) for i in range(6) for j in range(4)]
        for pos1 in position1:
            button1 = QPushButton()
            index1 = position1.index(pos1)
            try:
                _translate = QtCore.QCoreApplication.translate
                button1.setStyleSheet("QPushButton{background:%s}" % str(selfcolor[index1]))
                button1.setText(_translate("Color_Select",selfprint[index1]))
#            print(index1)
            except:
                pass
            button1.setObjectName("selfbuttonintable%s" % str(index1))
            button1.clicked.connect(partial(gettext,selfcolor[index1],button1.objectName()))
            self.selfdesigncolor_group.addWidget(button1, *pos1)
        self.layout.addLayout(self.selfdesigncolor_group)
        self.layout.setStretch(1, 1)
        self.layout.setStretch(3, 1)
        self.retranslateUi(Color_Select)
        self.buttonBox.accepted.connect(Color_Select.accept)
        self.buttonBox.rejected.connect(Color_Select.reject)
        QtCore.QMetaObject.connectSlotsByName(Color_Select)

    def retranslateUi(self, Color_Select):
        _translate = QtCore.QCoreApplication.translate
        Color_Select.setWindowTitle(_translate("Color_Select", "颜色选择"))
        self.default1.setText(_translate("Color_Select", "默认颜色"))
        self.selfdesigncolorgroup.setText(_translate("Color_Select", "自定义颜色"))

    def accept(self):
        pass

    def reject(self):
        pass

def gettext(colorintable,objectname12):
    global cm
    global yq
    global button
    global timer1
    global aa
#    print(objectname12)
    for i in range(24):
        index = re.search('[0-9]\d{1,2}|\d',objectname12).group(0)
#        print(index)
        objectname123 = objectname12.replace(str(index),str(i))
#        print(objectname123)
        object12345 = ysn123.findChild((QPushButton,),objectname123)
        object12345.resize(69,27)
    ysn1234 = ysn123.findChild((QPushButton,), objectname12)
    ysn1234.resize(69,30)
    yq = ""
    cm = colorintable
    aa = objectname12

def abcde():
    global cm
    return cm

def fghij():
    global yq
    return yq

def pqrst():#返回objectname判断是否为自定义颜色
    return aa
