# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\untitled\Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit

class Ui_Dialogname(object):
    def setupUi(self, Dialogname):
        global ysn1
        ysn1 = Dialogname
        Dialogname.setObjectName("Dialogname")
        Dialogname.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialogname)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.editlane = QtWidgets.QLineEdit(Dialogname)
        self.editlane.setGeometry(QtCore.QRect(80, 110, 191, 31))
        self.editlane.setObjectName("editlane")
        self.editlane.textChanged.connect(testcmy)
        self.retranslateUi(Dialogname)
        self.buttonBox.accepted.connect(Dialogname.accept)
        self.buttonBox.rejected.connect(Dialogname.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialogname)

    def retranslateUi(self, Dialogname):
        _translate = QtCore.QCoreApplication.translate
        Dialogname.setWindowTitle(_translate("Dialogname", "测试CMY选择"))

def testcmy():
    ysn12 = ysn1.findChild((QLineEdit,), "editlane")
    global ysn123
    ysn123 = ysn12.text()
    global selftestcmy
    selftestcmy = []
    selftestcmy = ysn123.split(":")
    if (len(selftestcmy) < 3):
        return
    try:
        selftestcmy[0] = ysn123.split(":")[0]
        selftestcmy[1] = ysn123.split(":")[1]
        selftestcmy[2] = ysn123.split(":")[2]
        #        print(selfcmy)
    except:
        return

def cmyset():
    return ysn123